### ISSUE TITLE
登录功能，账号输入限定了数字？

### ISSUE THREAD

**Issue by df13954** [seasonZhu/RxStudy#1]
2021年10月07日22:32:14，拉取最新master代码编译，在登录功能页面点击账号框，键盘显示纯数字，这个是bug吗，我的账号是英文的，输入框限制了只能输入数字。

mac 10.15.6
手机：6sp，13.6.1

**Comment by seasonZhu** [comment]
![image](https://user-images.githubusercontent.com/19945063/136874276-6d37cc31-90e8-4222-9da0-d7ce1487c779.png)
我目前这个输入框，写的就是弹出数字键盘。
因为我对玩安卓的登录业务不了解，以为只能通过手机注册，还有通过邮箱登录的吗？

**Comment by df13954** [comment]
> ![image](https://user-images.githubusercontent.com/19945063/136874276-6d37cc31-90e8-4222-9da0-d7ce1487c779.png) 我目前这个输入框，写的就是弹出数字键盘。 因为我对玩安卓的登录业务不了解，以为只能通过手机注册，还有通过邮箱登录的吗？

登录可以直接使用用户名登录的，比如xxxJoy这样，不限于手机号
