### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by ichbinwaber** [seasonZhu/RxStudy#2]
M1虚拟机运行，登录时，输入账户之后，密码框不可点击输入

**Comment by seasonZhu** [comment]
目前这个App仅提供了手机号登录。我刚刚在模拟器验证了一下，是好的。
![Snip20220407_6](https://user-images.githubusercontent.com/19945063/162100807-ef2e46d3-d340-4cd0-884b-132b0a1e88e1.png)

**Comment by seasonZhu** [comment]
已经验证，功能是好的。
