### ISSUE TITLE
文章右上角分享功能建议

### ISSUE THREAD

**Issue by df13954** [seasonZhu/RxStudy#3]
目前体验分享功能，找不到复制文字URL的地方，只能直接分享到某些app中，也不能在浏览器中打开文章，但是又不想分享到app中去。所以，大佬可以优化一下嘛。

**Comment by seasonZhu** [comment]
已安排，目前可以分享到粘贴板和Safari浏览器中。
但是需要注意的是粘贴板是标题+URL的形式，这个需要注意。

**Comment by df13954** [comment]
> 已安排，目前可以分享到粘贴板和Safari浏览器中。 但是需要注意的是粘贴板是标题+URL的形式，这个需要注意。

3q
