### ISSUE TITLE
编译一堆报错

### ISSUE THREAD

**Issue by chainliu0906** [seasonZhu/RxStudy#4]
编译一堆报错

**Comment by seasonZhu** [comment]
你至少要给截图呀。
需要使用Xcode14编译。

**Comment by chainliu0906** [comment]
我用的Xcode13

**Comment by zistylize** [comment]
同Xcode13  编译一堆报错 感觉用Xcode14也会一样报错的

<img width="320" alt="截屏2022-10-25 14 13 58" src="https://user-images.githubusercontent.com/15206914/197697429-469a82cd-cd51-46e7-8db8-c538ff4113f6.png">

<img width="744" alt="截屏2022-10-25 14 14 41" src="https://user-images.githubusercontent.com/15206914/197697484-a9482e6c-8316-4712-b216-1d23929d0c3a.png">

**Comment by seasonZhu** [comment]
使用Swift5.7的新语法，使用Xcode14就可以编译过了，你也可以看提交记录，查看对比。

**Comment by df13954** [comment]
我14.02正常啊

**Comment by zistylize** [comment]
好的 thx
