### ISSUE TITLE
 Showing Recent Issues File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a

### ISSUE THREAD

**Issue by zhangjianzhu** [seasonZhu/RxStudy#6]
<img width="1226" alt="企业微信截图_4cc33ab1-ae25-4a63-acdc-a379ea38e531" src="https://user-images.githubusercontent.com/18592113/230567779-0e9be350-57ae-4cfb-b90a-81ba0f8bfb1b.png">

刚接触iOS不久 ，这是什么原因啊

**Comment by seasonZhu** [comment]
尝试去找个一个libarclite_iphoneos.a的文件，丢到路径上。
可以看看这篇文章：https://juejin.cn/post/7224378915484172347。
